### ISSUE TITLE
Newline before EOF

### ISSUE THREAD

**Issue by bit2shift** [SimpleMachines/BuildTools#1]
`check-eof.php` should accept files ending with an empty line, otherwise Travis CI will fail for lots of valid files.
It's a _de facto_ standard to have 1 trailing newline in text files.

**Comment by MissAllSunday** [comment]
Yeah, we don't like to follow the masses 👅 
anyway, can't do that, our package manager loves ending php tags.

**Comment by MissAllSunday** [comment]
Indeed the packager manager will most likely receive a complete revamp on the next major version.
